### ISSUE TITLE
HTC website features/mockups 

### ISSUE THREAD

**Issue by micheleminno** [humanetech-community/humanetech-community-ideas#12]
Features we want to provide in the new HTC website.
They can be more easily represented by some drawing or mockups.

**Comment by micheleminno** [comment]
I think we should stick to the style / aspect of the [CHT website](http://humanetech.com/), as long as we are linked and reachable from their website.

**Comment by aschrijver** [comment]
I don't think we necessarily need to stick to CHT style. We are an independent community with different Mission and Vision. We have put considerable effort in positioning ourselves differently, having our own identity and now displaying a similar looking website will again prolong the confusion that we are just the CHT discussion forum (in the way we are mentioned on their website still).

But we can adopt the same fonts. Our logo is already similar to that of CHT, so that is good.

I suggest requirements for the landing page:

- Conveys the message that is in [**Be a Builder :heart: Help Improve Wellbeing, Freedom and Society**](https://community.humanetech.com/t/be-a-builder-help-improve-wellbeing-freedom-and-society/3322)

- Mentions and explains the Vision of _"Ubiquitous Humane Technology that Stimulates Humans to Flourish and Humanity to Thrive."_

- Mentions and explains the Mission of _"We Promote Solutions that Improve Wellbeing, Freedom and Society."_

- Introduces the concepts of The Pyramids of Humane Technology
  - Highlights the solution focus i.e. _"awareness of solutions"_
  - Highlights the four focus areas i.e. 4 pyramids
  - Highlights the relation _Humane Technnology --> Human Flourishing_ i.e. the 5th compound Pyramid of Human Flourishing

- We can use the simple colors of current pyramid images as part of the base palette and derive tints and shades from them

**Comment by aschrijver** [comment]
Easiest way to create a MVP would be to derive it from the current landing page at https://humanetech.community/

- Remove the photo header. Having a photo in the header means there should be a UX designer at work to match the color scheme.

- Create a simple header logo that has the - maybe - the compound pyramid in it and a background gradient.

- Edit the top headerbar sections to only include the minimum required:
  - **Forum**: Clickthrough to community.humanetech.com
  - **Blog**: We'll create a _Welcome_ blog post that guides through the site plus forum
  - **Docs**: All our documentation in one place with a Table of Contents on the left-hand side
  - **Activities**: A page that lists all our current projects & campaigns, forum groups, etc.
  - **Resources**: Our awesome list of external references, books, articles, etc.
  - **About**: Who we are, how we were founded, frequently asked questions

**Comment by micheleminno** [comment]
Also scrolling down in the landing page we can select some personal stories from the _Introductions_ topic, where now there's:

![Screenshot 2019-04-18 at 10 35 48](https://user-images.githubusercontent.com/832220/56347971-c4d11880-61c5-11e9-85c5-4d743eabef67.png)

**Comment by aschrijver** [comment]
Yes, those can be used for that purpose. That would be cool. Only problem is that the landing page has a very low information density (i.e. not much information fits without the page getting long).

**Comment by micheleminno** [comment]
Otherwise we can add another item in the menu dedicated to that:
- **Our stories**

**Comment by patmatsu** [comment]
>Resources: Our awesome list of external references, books, articles, etc.

I can work on this, though it will, of course, be a resource in progress.

**Comment by patmatsu** [comment]
> Otherwise we can add another item in the menu dedicated to that:
> 
>     * **Our stories**

I like this idea. Would help give the site personality and substance, especially if we add images.

**Comment by aschrijver** [comment]
That is great, but an 'Our stories' section and book lists, etc. should be part of the MVP. Just because we can't manage to get that up before 23rd of April. The 'Resources' page can hold a quick list of most interesting books though.

Right now we should go from the [Community Website](https://humanetech.community) and create some content for the (now still broken) links in the mockup.

Let's move all the discussion about this MVP to the [Issue Tracker of the Community Website](https://github.com/humanetech-community/community-hub/issues)

**Comment by aschrijver** [comment]
I created a new top-level issue in the Community Hub repo with a quick breakdown of some tasks, where we can work from.

More tasks can be added. Keeping them as simple as possible allows for quickly perfoming the task and closing of the issue.

Here is the top-level task:

# [Create community website MVP](https://github.com/humanetech-community/community-hub/issues/12) 

(https://github.com/humanetech-community/community-hub/issues/12)

**Comment by aschrijver** [comment]
I created a project board where we can track the progress of the tasks:

# [Community Hub MVP Project](https://github.com/humanetech-community/community-hub/projects/1)
