### ISSUE TITLE
Add Instagram icon on the forum header

### ISSUE THREAD

**Issue by micheleminno** [humanetech-community/humanetech-community-ideas#13]

**Comment by aschrijver** [comment]
This was requested by Siddhi on CT message too. My answer:

----

Maybe we could, but there is one problem: Mobile. On mobile phones this starts to look cluttered. On my Samsung S7 there is just enough space for one more icon, but then all space is 100% occupied. On smalller form factors the extra icon will not fit and the layout looks bad.

Right now Twitter is there, because it is most common practice to show the Twitter feed, and it is where public announcements are made first.
Github and the Community Hub are there because those places is where the community does work.

----

Siddhi: Is there anyway to resize the icons?

----

No, there is not. I was previously even thinking of removing the Twitter icon to only show ‘specialty’ icons. We have the whole range (well almost) of social media channels in the footer of the website…

---> Note: You can make icons smaller via CSS, but then also the Menu and Search get smaller, looks bad.

Channels are mentioned on the [Community Hub](https://humanetech.community) which we should promote as the first go-to point for the community anyway.

Below is the current footer of the Community Hub. The “Reinforce our message” can include Insta too, and placed in different places. The website code also has features to show below each blog post and even docs a “Share this message” block with logo’s of social media channels…

![community website footer](https://discourse-cdn-sjc2.com/standard10/uploads/humanetech/optimized/2X/6/6ed255657a2791663a324d14cf6a4fb40588ee12_2_690x294.png)

**Comment by aschrijver** [comment]
Suggesting to close this issue.
