### ISSUE TITLE
Manually revise all existent topics to assign to them the most fitting new categories

### ISSUE THREAD

**Issue by micheleminno** [humanetech-community/humanetech-community-ideas#9]
It's a big work, we have to split topics according to our focus of interest (visualized by a specific pyramid).

**Comment by patmatsu** [comment]
Not sure how to do this. Can you explain for us laypeople what's involved?

**Comment by aschrijver** [comment]
This involves taking one new category, then look at an old category that needs to be migrated, and one by one open the topic and decide whether it fits the new category. If yes, you can edit + change the category, and add e.g. appropriate tags at the same time.

Some topics are very long and people went off-topic in the thread. If the off-topic posts constitute a worthwile subject area that can stand on its own, they should be split to a new topic for which you give the title + category + tags, and then move the appropriate posts in them.

This activity is a lot of work, but it is good to learn how to do this, because it would be best to have this as an **ongoing moderators task**, so the work stays minimal after the large cleanup job we have now.

**Comment by ghost** [comment]
Thanks for clarification! I guess this can start once [new category structure issue ](https://github.com/humanetech-community/engagement-ideas/issues/7) is solved and new categories are posted on forum's web site. Or is there any way how to do that right now?

**Comment by aschrijver** [comment]
Yes, you are right. Also it needs moderator privilege. I suggest we can add 3 more moderators, taking the place of `@metasj`, @Mamie` and `@lydialaurenson`, because they are fully inactive.

If they want to rejoin the community in moderator or admin privilege this can be done later when there are more free slots available in our subscription.. I will create a CT post to ask who wants to become a moderator.

**Comment by aschrijver** [comment]
With the forum reorganization complete, this issue is done. Improving categorization is an ongoing task for forum moderators.
